export const LOCO_HEADER_SIZE = 22;
export const LOCO_METHOD_SIZE = 11;
export const LOCO_DEFAULT_MAX_PAYLOAD_SIZE = 8 * 1024 * 1024;
export const LOCO_DEFAULT_MAX_BUFFERED_BYTES = LOCO_DEFAULT_MAX_PAYLOAD_SIZE * 2;
